### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by funasoul** [funalab/MaLoN#1]
1. The execution and installation examples should use python venv. Please refer to the NVAN example ( https://github.com/funalab/NVAN )
2. Image (screenshot is broken)

**Comment by hikiki-no-ki** [comment]
I have updated README following your comments.

1. Installation guides and the dependency were added to README following format example of NVAN repository (https://github.com/funalab/NVAN ).
2. images branch was pushed and screenshot was fixed.
